[package]
name = "github-dev-app"
version = "0.1.0"
edition = "2021"

description = "A command-line tool that creates GitHub Apps for local development"
repository = "https://github.com/otterbuild/github-dev-app"
license = "MIT OR Apache-2.0"

[dependencies]
